import os
import pandas as pd
import numpy as np
import ta
from src.utils.logger import get_logger

logger = get_logger(__name__)

class FeatureEngineer:
    """
    Service to engineer exhaustive features for machine learning models.
    """
    def __init__(self):
        self.base_dir = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
        self.input_filepath = os.path.join(self.base_dir, "data", "processed", "goldbees_cleaned.csv")
        self.output_filepath = os.path.join(self.base_dir, "data", "processed", "goldbees_features.csv")

    def load_data(self) -> pd.DataFrame:
        if not os.path.exists(self.input_filepath):
            raise FileNotFoundError(f"Cleaned data not found at {self.input_filepath}")
        df = pd.read_csv(self.input_filepath)
        df['Date'] = pd.to_datetime(df['Date'])
        df.set_index('Date', inplace=True)
        return df

    def generate_features(self):
        logger.info("Starting Comprehensive Feature Engineering...")
        try:
            df = self.load_data()
            
            # --- Technical Indicators using `ta` package ---
            logger.info("Generating Trend Indicators (SMA, EMA, MACD, ADX, CCI)...")
            # SMA & EMA
            df['SMA_20'] = ta.trend.sma_indicator(df['Close'], window=20)
            df['SMA_50'] = ta.trend.sma_indicator(df['Close'], window=50)
            df['EMA_20'] = ta.trend.ema_indicator(df['Close'], window=20)
            
            # MACD
            df['MACD'] = ta.trend.macd(df['Close'])
            df['MACD_Signal'] = ta.trend.macd_signal(df['Close'])
            
            # ADX
            df['ADX'] = ta.trend.adx(df['High'], df['Low'], df['Close'])
            
            # CCI
            df['CCI'] = ta.trend.cci(df['High'], df['Low'], df['Close'])
            
            logger.info("Generating Momentum Indicators (RSI, ROC, Momentum)...")
            # RSI
            df['RSI'] = ta.momentum.rsi(df['Close'], window=14)
            # ROC
            df['ROC'] = ta.momentum.roc(df['Close'], window=10)
            # Momentum (10-day diff)
            df['Momentum'] = df['Close'].diff(periods=10)
            
            logger.info("Generating Volatility Indicators (Bollinger Bands, ATR)...")
            # Bollinger Bands
            df['BB_High'] = ta.volatility.bollinger_hband(df['Close'], window=20, window_dev=2)
            df['BB_Low'] = ta.volatility.bollinger_lband(df['Close'], window=20, window_dev=2)
            
            # ATR
            df['ATR'] = ta.volatility.average_true_range(df['High'], df['Low'], df['Close'], window=14)
            
            logger.info("Generating Volume Indicators (VWAP, OBV)...")
            # VWAP
            df['VWAP'] = ta.volume.volume_weighted_average_price(df['High'], df['Low'], df['Close'], df['Volume'])
            # OBV
            df['OBV'] = ta.volume.on_balance_volume(df['Close'], df['Volume'])
            
            # --- Returns & Basic Volatility ---
            logger.info("Generating Returns & Volatility...")
            df['Daily_Return'] = df['Close'].pct_change()
            df['Log_Return'] = np.log(df['Close'] / df['Close'].shift(1))
            df['Volatility_20'] = df['Daily_Return'].rolling(window=20).std()
            
            # --- Rolling Statistics ---
            logger.info("Generating Rolling Statistics...")
            df['Rolling_Mean_20'] = df['Close'].rolling(window=20).mean()
            df['Rolling_Std_20'] = df['Close'].rolling(window=20).std()
            df['Rolling_Max_20'] = df['Close'].rolling(window=20).max()
            df['Rolling_Min_20'] = df['Close'].rolling(window=20).min()
            
            # --- Calendar Features ---
            logger.info("Generating Calendar Features...")
            df['Month'] = df.index.month
            df['Quarter'] = df.index.quarter
            df['Weekday'] = df.index.weekday
            # Simple Holiday Flag: if volume is anomalously low or using an external calendar.
            # Here we just put a placeholder for potential future advanced implementations.
            df['Holiday_Flag'] = 0 
            
            # --- Lag Features ---
            logger.info("Generating Lag Features...")
            for i in [1, 2, 3, 5, 10]:
                df[f'Close_Lag_{i}'] = df['Close'].shift(i)
                df[f'Volume_Lag_{i}'] = df['Volume'].shift(i)

            # Drop missing values generated by rolling windows/lags (usually first ~50 rows)
            initial_len = len(df)
            df.dropna(inplace=True)
            logger.info(f"Dropped {initial_len - len(df)} rows due to NaN from indicator lookback periods.")
            
            # Save engineered dataset
            df.reset_index(inplace=True)
            df.to_csv(self.output_filepath, index=False)
            
            logger.info(f"Feature Engineering complete! Engineered dataset saved to {self.output_filepath}")
            logger.info(f"Final dataset shape: {df.shape}")
            
        except Exception as e:
            logger.error(f"Error during Feature Engineering: {str(e)}")

if __name__ == "__main__":
    engineer = FeatureEngineer()
    engineer.generate_features()
